#!/bin/sh

echo "Remove autom4te.cache directory"
rm -rf autom4te.cache

echo "Remove configure script"
rm -f configure

echo "Remove Makefile.in files"
find . -type f -name 'Makefile.in' -exec rm {} \;
find . -type f -name 'Makefile' -exec rm {} \;

echo "Remove files generated by libtoolize"
rm -rf m4
rm -rf ltmain.sh
echo "Remove files generated by automake"
rm -f compile
rm -f config.guess
rm -f config.sub
rm -f config.h.in*
rm -f config.log
rm -rf config.status
rm -f config.h
rm -f libndpi.pc
rm -f install-sh
rm -f missing
rm -f test-driver
rm -f depcomp


rm -rf build

echo "Remove remaining generated files"
rm -f aclocal.m4
rm -f stamp-*
if [ -f "/usr/local/bin/ndpiReaderCPP" ]; then
	rm -rf /usr/local/bin/ndpiReaderCPP
fi

find . -type d -name "*.deps*" -exec rm -rf {} \;


